baseURL = 'https://ivarsidorsson.work/'
languageCode = 'en-us'
title = 'Ivar Sidorsson'


[markup]
[markup.highlight]
style = 'gruvbox'

[taxonomies]
role = 'roles'

[caches]
[caches.images]
dir = ':cacheDir/images'